// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDT2i1ckke3TglqzZ-SClw80xU6r5COXmk",
    authDomain: "sayit-dc5dc.firebaseapp.com",
    projectId: "sayit-dc5dc",
    storageBucket: "sayit-dc5dc.appspot.com",
    messagingSenderId: "578805552376",
    appId: "1:578805552376:web:12449e5ed493ca422c970d",
    measurementId: "G-SWEVZ5Q9L3",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRN9kA-MutRKLoCrvvkA5OLmDp7AN1Ecg',
    appId: '1:578805552376:android:b76fc86fd04197322c970d',
    messagingSenderId: '578805552376',
    projectId: 'sayit-dc5dc',
    storageBucket: 'sayit-dc5dc.appspot.com',
  );
}
